# HTTP for admin (default) and redirect api domain to HTTPS
server {
  listen 80;
  server_name api.ooooooo0hmygooooooo0sh.xyz;
  return 301 https://$host$request_uri;
}

server {
  listen 80;
  server_name _;

  location /api/ {
    proxy_pass http://api:8080/;
  }

  location /admin/ {
    proxy_pass http://api:8080/admin/;
  }

  location / {
    proxy_pass http://admin:80/;
  }
}

# HTTPS for API domain
server {
  listen 443 ssl;
  server_name api.ooooooo0hmygooooooo0sh.xyz;

  ssl_certificate /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/privkey.pem;

  location /api/ {
    proxy_pass http://api:8080/;
  }

  location /callback/ {
    proxy_pass http://api:8080/callback/;
  }

  location /tags {
    proxy_pass http://api:8080/tags;
  }

  location /generate {
    proxy_pass http://api:8080/generate;
  }

  location /users {
    proxy_pass http://api:8080/users;
  }

  location /init-tags {
    proxy_pass http://api:8080/init-tags;
  }

  location /songs {
    proxy_pass http://api:8080/songs;
  }

  location /feedback {
    proxy_pass http://api:8080/feedback;
  }
}
