server {
  listen 80;
  server_name _;

  location /admin/ {
    proxy_pass http://api:8080/admin/;
    proxy_set_header Host $host;
  }

  location /generate {
    proxy_pass http://api:8080/generate;
  }

  location /tags {
    proxy_pass http://api:8080/tags;
  }

  location /users {
    proxy_pass http://api:8080/users;
  }

  location /init-tags {
    proxy_pass http://api:8080/init-tags;
  }

  location /songs {
    proxy_pass http://api:8080/songs;
  }

  location /feedback {
    proxy_pass http://api:8080/feedback;
  }

  location /callback/ {
    proxy_pass http://api:8080/callback/;
  }

  location / {
    proxy_pass http://admin:80/;
  }
}
