server {
  listen 80 default_server;
  server_name _;

  location /admin/ {
    proxy_pass http://api:8080/admin/;
  }

  location / {
    proxy_pass http://admin:80/;
  }
}

server {
  listen 80;
  server_name api.ooooooo0hmygooooooo0sh.xyz;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl default_server;
  server_name _;

  ssl_certificate /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/privkey.pem;

  location /admin/ {
    proxy_pass http://api:8080/admin/;
  }

  location = /tags {
    proxy_pass http://api:8080/tags;
  }

  location = /generate {
    proxy_pass http://api:8080/generate;
  }

  location = /users {
    proxy_pass http://api:8080/users;
  }

  location = /init-tags {
    proxy_pass http://api:8080/init-tags;
  }

  location = /songs {
    proxy_pass http://api:8080/songs;
  }

  location = /feedback {
    proxy_pass http://api:8080/feedback;
  }

  location = /playlists {
    proxy_pass http://api:8080/playlists;
  }

  location = /favorites {
    proxy_pass http://api:8080/favorites;
  }

  location = /my-created-songs {
    proxy_pass http://api:8080/my-created-songs;
  }

  location /api/ {
    proxy_pass http://api:8080/;
  }

  location /callback/ {
    proxy_pass http://api:8080/callback/;
  }

  location / {
    proxy_pass http://admin:80/;
  }
}

server {
  listen 443 ssl;
  server_name api.ooooooo0hmygooooooo0sh.xyz;

  ssl_certificate /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/api.ooooooo0hmygooooooo0sh.xyz/privkey.pem;

  location = /tags {
    proxy_pass http://api:8080/tags;
  }

  location = /generate {
    proxy_pass http://api:8080/generate;
  }

  location = /users {
    proxy_pass http://api:8080/users;
  }

  location = /init-tags {
    proxy_pass http://api:8080/init-tags;
  }

  location = /songs {
    proxy_pass http://api:8080/songs;
  }

  location = /feedback {
    proxy_pass http://api:8080/feedback;
  }

  location = /playlists {
    proxy_pass http://api:8080/playlists;
  }

  location = /favorites {
    proxy_pass http://api:8080/favorites;
  }

  location = /my-created-songs {
    proxy_pass http://api:8080/my-created-songs;
  }

  location /api/ {
    proxy_pass http://api:8080/;
  }

  location /callback/ {
    proxy_pass http://api:8080/callback/;
  }
}
