ALTER TABLE tags ADD COLUMN IF NOT EXISTS is_system BOOLEAN DEFAULT TRUE;
ALTER TABLE user_tags
  ADD COLUMN IF NOT EXISTS initial_weight NUMERIC DEFAULT 0.3,
  ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS update_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE song_tags ADD COLUMN IF NOT EXISTS relevance NUMERIC DEFAULT 1.0;
