ALTER TABLE songs
  ADD COLUMN IF NOT EXISTS source_song_id INT REFERENCES songs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS generation_mode TEXT DEFAULT 'generated',
  ADD COLUMN IF NOT EXISTS reuse_count INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_available BOOLEAN DEFAULT TRUE;
