ALTER TABLE user_tags
  ADD COLUMN IF NOT EXISTS raw_score NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS softmax_weight NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_anchor BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS anchor_floor NUMERIC DEFAULT 0.3;

ALTER TABLE generation_jobs
  ADD COLUMN IF NOT EXISTS strategy_mode TEXT DEFAULT 'stable',
  ADD COLUMN IF NOT EXISTS exploration_level TEXT DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS prompt_debug JSONB DEFAULT '{}'::jsonb;

ALTER TABLE user_song_queue
  ADD COLUMN IF NOT EXISTS queue_bucket TEXT DEFAULT 'primary';
