FROM nginx:1.27-alpine
COPY index.html /usr/share/nginx/html/index.html
COPY styles.css /usr/share/nginx/html/styles.css
COPY app.js /usr/share/nginx/html/app.js
COPY users.html /usr/share/nginx/html/users.html
COPY users.js /usr/share/nginx/html/users.js
COPY tags.html /usr/share/nginx/html/tags.html
COPY tags.js /usr/share/nginx/html/tags.js
